"""Generate lib/src/yamnet_labels.dart from the label list embedded in assets/yamnet.tflite.

Usage:
    python3 tool/generate_yamnet_labels.py
"""

import io
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    model = (ROOT / "assets/yamnet.tflite").read_bytes()
    # The TFLite metadata appends a zip archive that holds yamnet_label_list.txt.
    archive = zipfile.ZipFile(io.BytesIO(model[model.index(b"PK\x03\x04"):]))
    labels = archive.read("yamnet_label_list.txt").decode("utf-8").splitlines()
    lines = ["// Generated by tool/generate_yamnet_labels.py from assets/yamnet.tflite. Do not edit.", "", "const List<String> yamnetLabels = ["]
    lines += ["  " + '"' + label.replace("\\", "\\\\").replace('"', '\\"') + '",' for label in labels]
    lines += ["];", ""]
    (ROOT / "lib/src/yamnet_labels.dart").write_text("\n".join(lines))
    print(f"{len(labels)} labels")


if __name__ == "__main__":
    main()
